### ISSUE TITLE
Small issue converting

### ISSUE THREAD

**Issue by ghost** [binxio/serverless-cfnflip#3]
Tried to convert this: https://s3.amazonaws.com/aws-configservice-us-east-1/cloudformation-templates-for-managed-rules/IAM_USER_GROUP_MEMBERSHIP_CHECK.template

The condition did not come out right. 

It should be:

```yaml
Conditions:
  groupNames: !Not
    - !Equals
      - ''
      - !Ref groupNames
``` 

But it comes out as 
```yaml
Conditions:
  groupNames: !Not
    - !Equals
      - ''
```
